[package]
name = "testmaturin"
version = "0.1.0"
edition = "2021"
description = "my cool maturin package"
license = "FSFUL"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "testmaturin"
crate-type = ["cdylib"]

[dependencies]
